apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bank-of-anthos
  namespace: bank-of-anthos
  labels:
    app: bank-of-anthos
spec:
  securityPolicy:
    name: bank-of-anthos
  healthCheck:
    checkIntervalSec: 2
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 10
    type: HTTP
    requestPath: /
  iap:
    enabled: false
    oauthclientCredentials:
      secretName: iap-secret