apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: bank-of-anthos
  namespace: bank-of-anthos
  labels:
    app: bank-of-anthos
spec:
  domains:
    - boa.136.110.128.154.sslip.io