apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: appodoodemo390a
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '3'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: europe-west1-docker.pkg.dev/qwiklabs-gcp-00-184743bf2918/odoo-demo-390a/odoo:latest-qa
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: DB_USER
          value: appodoodemo390aqa
        - name: DB_NAME
          value: appodoodemo390aqa
        - name: DB_HOST
          value: 172.20.0.3
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: cloud-sql-db-390a-odooqa-password-demo-390a
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
        volumeMounts:
        - name: nfs-data-volume
          mountPath: /mnt
        - name: gcs-addon-volume
          mountPath: /extra-addons
        livenessProbe:
          initialDelaySeconds: 180
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            path: /web/health
            port: 80
        startupProbe:
          timeoutSeconds: 120
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 80
      volumes:
      - name: gcs-addon-volume
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: qwiklabs-gcp-00-184743bf2918-data
      - name: nfs-data-volume
        nfs:
          server: 10.142.192.2
          path: /share/appodoodemo390aqa
