ARG APP_VERSION=latest
FROM wordpress:${APP_VERSION}

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
