return [
	authorizationLevel: null,
	authorizationType: null,
	context: null,
	event: null,
	extensionPoint: null,
	fromAccount: null,
	fromOwner: null,
	fromOwnerResult: null,
	installment: null,
	newtatus: null,
	oldStatus: null,
	paymentType: null,
	performTransaction: null,
	preview: null,
	toAccount: null,
	toOwner: null,
	toOwnerResult: null,
	transaction: null,

]
