return [
	entityId: null,
	entityIdParam: null,
	execution: null,
	identityProvider: null,
	inviteToken: null,
	location: null,
	mobileUrlFilePart: null,
	paymentAmount: null,
	paymentCustomValues: null,
	paymentDescription: null,
	paymentTo: null,
	paymentType: null,
	replyTo: null,
	requestId: null,
	storage: null,
	ticket: null,
	type: null,
	unsubscribeEmailKey: null,
	unsubscribeEmailType: null,
	urlFilePart: null,
	user: null,
	validationKey: null,
	voucher: null,

]
