return [
	ad: null,
	contact: null,
	contactInfo: null,
	customOperation: null,
	document: null,
	execution: null,
	field: null,
	formParameters: null,
	fromOwner: null,
	fromOwnerResult: null,
	menuItem: null,
	operator: null,
	paymentType: null,
	record: null,
	step: null,
	storage: null,
	toOwner: null,
	toOwnerResult: null,
	transfer: null,
	user: null,
	voucher: null,
	voucherCreationType: null,
	voucherType: null,
	wizard: null,

]
